#!/system/bin/sh
# Tuxafgmur - Dhollmen

rm -fr /data/bugreports
rm -fr /data/dontpanic
rm -f  /data/local/tmp/*
rm -f  /data/tombstones/*
rm -f  /data/system/uiderrors.txt
rm -f  /data/system/dropbox/*

cd /data/dalvik-cache/
if [ "$?" != "0" ]; then
	for q in *; do
		a=$(echo $q|cut -d'@' -f1)
		b=$(echo $q|cut -d'@' -f2)
		c=$(echo $q|cut -d'@' -f3)
		case $c in
			boot.art)
			;;
			boot.oat)
			;;
			*)	FILE="/$a/$b/$c"
				[ -e $FILE ] || rm $q
			;;
		esac
	done
fi

mount -o remount,rw,noatime,nodiratime /system
rm /system/etc/init.d/90-Clean
mount -o remount,ro,noatime,nodiratime /system
