#!/system/bin/sh
# Copyright 2014 Tuxafgmur - Dhollmen

[ -f /data/.lastclean ] && . /data/.lastclean

LASTDATE=$(($LASTDATE + 604800))

TODAY=$(date -u +%s)

if [ $TODAY -ge $LASTDATE ]; then
	rm -fr /data/bugreports
	rm -fr /data/dontpanic
	rm -f  /data/local/tmp/*
	rm -f  /data/tombstones/*
	rm -f  /data/system/uiderrors.txt
	rm -f  /data/system/dropbox/*

	cd /data/dalvik-cache/
	if [ "$?" != "0" ]; then
		for q in *; do
			a=$(echo $q|cut -d'@' -f1)
			b=$(echo $q|cut -d'@' -f2)
			c=$(echo $q|cut -d'@' -f3)
			case $c in
				boot.art)
				;;
				boot.oat)
				;;
				*)	FILE="/$a/$b/$c"
					[ -e $FILE ] || rm $q
				;;
			esac
		done
	fi

	LASTDATE=$TODAY
	echo "LASTDATE=$LASTDATE" > /data/.lastclean
fi
