#!/system/bin/sh
# Copyright 2014-2015 Tuxafgmur -Dhollmen

[ -f /data/.lasttrim ] && . /data/.lasttrim

LASTDATE=$(($LASTDATE + 432000))

TODAY=$(date -u +%s)

if [ $TODAY -ge $LASTDATE ]; then
	for mount in /system /cache /data /preload; do
		fstrim $mount >/dev/null 2>&1
	done
	LASTDATE=$TODAY
	echo "LASTDATE=$LASTDATE" > /data/.lasttrim
fi
